<script setup lang="ts">
import { Bot, LogOut } from 'lucide-vue-next'
import { Button } from '@/components/ui/button'
import { useConsoleStore } from '~/composables/useConsoleStore'

const store = useConsoleStore()
const { t, view, openConsole, sidebarCollapsed, account, siteSettings, generalNav, billingNav, personalNav, managementNav, signOut } = store
</script>

<template>
  <aside class="app-sidebar sticky top-0 flex h-screen w-60 shrink-0 flex-col border-r border-border bg-card/50 transition-[width] lg:w-60" :class="{ 'lg:w-16': sidebarCollapsed }">
    <div class="flex h-16 items-center gap-3 px-5"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm"><Bot :size="20" /></span><span v-show="!sidebarCollapsed" class="min-w-0 truncate text-[15px] font-bold tracking-tight">{{ siteSettings.name }}</span></div>
    <nav class="flex-1 overflow-y-auto px-3 pt-2 pb-3">
      <div class="mb-4"><p class="px-2.5 pb-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground/70">{{ t('general') }}</p><button v-for="[id, label, Icon] in generalNav" :key="id" class="flex w-full items-center gap-3 rounded-lg px-2.5 py-2 text-left text-[13px] leading-snug transition-all duration-150 hover:bg-accent" :class="view === id ? 'bg-accent font-semibold text-accent-foreground shadow-sm' : 'text-muted-foreground'" @click="openConsole(id)"><component :is="Icon" :size="16" class="shrink-0" /><span v-show="!sidebarCollapsed" class="truncate">{{ label }}</span></button></div>
      <div class="mb-4"><p class="px-2.5 pb-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground/70">{{ t('billing') }}</p><button v-for="[id, label, Icon] in billingNav" :key="id" class="flex w-full items-center gap-3 rounded-lg px-2.5 py-2 text-left text-[13px] leading-snug transition-all duration-150 hover:bg-accent" :class="view === id ? 'bg-accent font-semibold text-accent-foreground shadow-sm' : 'text-muted-foreground'" @click="openConsole(id)"><component :is="Icon" :size="16" class="shrink-0" /><span v-show="!sidebarCollapsed" class="truncate">{{ label }}</span></button></div>
      <div class="mb-4"><p class="px-2.5 pb-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground/70">{{ t('personal') }}</p><button v-for="[id, label, Icon] in personalNav" :key="id" class="flex w-full items-center gap-3 rounded-lg px-2.5 py-2 text-left text-[13px] leading-snug transition-all duration-150 hover:bg-accent" :class="view === id ? 'bg-accent font-semibold text-accent-foreground shadow-sm' : 'text-muted-foreground'" @click="openConsole(id)"><component :is="Icon" :size="16" class="shrink-0" /><span v-show="!sidebarCollapsed" class="truncate">{{ label }}</span></button></div>
      <div v-if="managementNav.length" class="mb-4"><p class="px-2.5 pb-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground/70">{{ t('management') }}</p><button v-for="[id, label, Icon] in managementNav" :key="id" class="flex w-full items-center gap-3 rounded-lg px-2.5 py-2 text-left text-[13px] leading-snug transition-all duration-150 hover:bg-accent" :class="view === id ? 'bg-accent font-semibold text-accent-foreground shadow-sm' : 'text-muted-foreground'" @click="openConsole(id)"><component :is="Icon" :size="16" class="shrink-0" /><span v-show="!sidebarCollapsed" class="truncate">{{ label }}</span></button></div>
    </nav>
    <div class="border-t border-border px-4 py-3.5"><div class="mb-3 flex items-center gap-2.5 text-xs text-muted-foreground"><span class="h-2 w-2 shrink-0 animate-pulse rounded-full bg-green-500" /><span class="min-w-0"><b class="block text-foreground/90">{{ t('gatewayOnline') }}</b><small class="text-[11px]">{{ t('serviceRunning') }}</small></span></div><div class="flex items-center gap-2.5"><i class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground shadow-sm">{{ account?.name?.slice(0, 1) || '?' }}</i><span v-show="!sidebarCollapsed" class="min-w-0 flex-1"><b class="block truncate text-[13px] font-semibold text-foreground">{{ account?.name || t('loadingLabel') }}</b><small class="text-[11px] text-muted-foreground">{{ account?.role || t('accountLabel') }}</small></span><Button v-show="!sidebarCollapsed" variant="ghost" size="icon-sm" :aria-label="t('actionAccountLogout')" :title="t('actionAccountLogout')" @click="signOut"><LogOut :size="15" /></Button></div></div>
  </aside>
</template>